[tools]
aws = "latest"
codex = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
java = "21"
jq = "latest"
jwt = "latest"
node = "24"
python = "3.13.1"
ripgrep = "latest"
rust = "latest"
uv = "latest"
"aqua:pranshuparmar/witr" = "latest"
yarn = "latest"
